plugins {
  id "com.android.application" version "7.4.2" apply false
}

allprojects {
  repositories {
    // Tenta Google primeiro, mas com fallback
    maven { url "https://maven.google.com/" }
    mavenCentral()
    maven { url "https://repo.gradle.org/gradle/libs-releases" }
  }
}

subprojects {
  repositories {
    maven { url "https://maven.google.com/" }
    mavenCentral()
    maven { url "https://repo.gradle.org/gradle/libs-releases" }
  }
}
