window.EN = window.EN || {};

/*
 * Bestiário — dados de todas as criaturas da primeira região (Sítio/Mata do
 * Cedro), com identidade de folclore brasileiro. A maioria das entradas é
 * SOMENTE DADOS nesta etapa (`implemented:false`): define categoria, lore,
 * comportamento e regras de aparição para orientar produção futura, sem
 * inflar o escopo deste protótipo com IA/arte para 19 criaturas de uma vez.
 *
 * Apenas as marcadas `implemented:true` têm IA e sprite funcionando no
 * mundo/arena agora: Rato-do-Mato Corrompido e Cipó Vivo — escolhidas por
 * representarem as duas categorias mais comuns (HOSTIL vs TERRITORIAL) com
 * comportamentos claramente diferentes.
 *
 * category: 'hostile' | 'territorial' | 'neutral' | 'guardian' | 'narrative' | 'boss'
 */
EN.Bestiary = (function () {
  var CATEGORY_LABEL = {
    hostile: "Hostil",
    territorial: "Territorial",
    neutral: "Neutra",
    guardian: "Guardiã",
    narrative: "Narrativa",
    boss: "Chefe",
  };

  var list = [
    {
      id: "rato_mato_corrompido",
      name: "Rato-do-Mato Corrompido",
      category: "hostile",
      habitat: "Sítio, bordas da Mata do Cedro",
      schedule: "any",
      behavior: "Patrulha território curto; persegue ao avistar o jogador; avisa antes de morder.",
      aggressiveness: 2,
      attacks: ["Mordida"],
      weaknesses: ["Dano físico"],
      resistances: [],
      drops: ["Vintém", "Pelo Corrompido"],
      lore: "Um rato comum que bebeu água próxima a uma raiz negra vinda da Mina Santa Luzia.",
      veioRelation: "Vítima de contaminação leve — não é natural da espécie.",
      corruptionVisual: "Pequenas rachaduras escuras no pelo, olhos alaranjados.",
      implemented: true,
    },
    {
      id: "vagalume_de_defunto",
      name: "Vagalume de Defunto",
      category: "hostile",
      habitat: "Mata do Cedro, Brejo das Lanternas",
      schedule: "night",
      behavior: "Aparece em grupos pequenos à noite; voa em padrão errático; luz confunde o jogador.",
      aggressiveness: 2,
      attacks: ["Luz Confusa (inverte controles por instantes)", "Toque Elétrico"],
      weaknesses: ["Dano mágico"],
      resistances: ["Dano físico leve"],
      drops: ["Pó de Vagalume"],
      lore: "Diz-se que carregam a última luz de quem se perdeu na mata sem encontrar o caminho de volta.",
      veioRelation: "Naturalmente ligado ao Encantado — só fica hostil perto de Veios perturbados.",
      corruptionVisual: "Luz que pulsa em vermelho em vez de amarelo quando corrompido.",
      implemented: true,
    },
    {
      id: "cipo_vivo",
      name: "Cipó Vivo",
      category: "territorial",
      habitat: "Mata do Cedro, moitas densas",
      schedule: "any",
      behavior: "Fica enraizado em um ponto fixo; ignora o jogador à distância; agarra quem entra na área por tempo demais.",
      aggressiveness: 1,
      attacks: ["Agarrar", "Imobilizar", "Puxão"],
      weaknesses: ["Fogo", "Corte"],
      resistances: ["Perfuração"],
      drops: ["Fibra Encantada"],
      lore: "Uma planta que absorveu tanta energia do Veio que ganhou vontade própria — e território a defender.",
      veioRelation: "Cresce diretamente sobre pontos de vazamento do Veio.",
      corruptionVisual: "Nervuras negras pulsantes correndo pelo caule.",
      implemented: true,
    },
    {
      id: "tatu_de_pedra",
      name: "Tatu de Pedra",
      category: "hostile",
      habitat: "Mina Santa Luzia, pedreiras",
      schedule: "any",
      behavior: "Defensivo por padrão; enrola-se e realiza investidas em linha reta quando provocado.",
      aggressiveness: 2,
      attacks: ["Investida em Rolamento"],
      weaknesses: ["Impacto quando enrolado"],
      resistances: ["Corte", "Perfuração"],
      drops: ["Placa de Casco"],
      lore: "Sua casca mineralizou com o tempo perto de veios de minério corrompido.",
      veioRelation: "Contaminação mineral, não espiritual.",
      corruptionVisual: "Vetas de minério escuro visíveis entre as placas do casco.",
      implemented: false,
    },
    {
      id: "morcego_da_mina",
      name: "Morcego da Mina",
      category: "hostile",
      habitat: "Mina Santa Luzia",
      schedule: "any (interior escuro)",
      behavior: "Voa em bando; ataques rápidos e erráticos em rajada.",
      aggressiveness: 3,
      attacks: ["Investida em Rajada"],
      weaknesses: ["Dano em área"],
      resistances: [],
      drops: ["Asa Membranosa"],
      lore: "Colônia comum na mina, agora agitada pelas raízes negras que avançam pelas galerias.",
      veioRelation: "Território diretamente afetado pela contaminação da mina.",
      corruptionVisual: "Pelagem com manchas escuras, voo mais errático que o normal.",
      implemented: true,
    },
    {
      id: "sapo_de_pedra",
      name: "Sapo de Pedra",
      category: "hostile",
      habitat: "Rio das Pedras, câmaras úmidas da mina",
      schedule: "any",
      behavior: "Estacionário até ser provocado; alta defesa; ataques lentos e previsíveis.",
      aggressiveness: 1,
      attacks: ["Língua Pesada", "Salto Esmagador"],
      weaknesses: ["Dano mágico"],
      resistances: ["Dano físico"],
      drops: ["Pedra Úmida", "Veneno de Sapo"],
      lore: "Guardião lento das poças mais fundas — quase nunca ataca primeiro.",
      veioRelation: "Nenhuma — inimigo comum, não corrompido.",
      corruptionVisual: null,
      implemented: true,
    },
    {
      id: "cao_da_estrada",
      name: "Cão da Estrada",
      category: "hostile",
      habitat: "Estrada Velha",
      schedule: "madrugada",
      behavior: "Só se manifesta na madrugada; segue viajantes solitários por longas distâncias antes de atacar.",
      aggressiveness: 3,
      attacks: ["Perseguição", "Mordida Sombria"],
      weaknesses: ["Luz", "Dano mágico"],
      resistances: ["Medo (imune)"],
      drops: ["Coleira Enferrujada"],
      lore: "Assombração de um cão que morreu protegendo seu dono numa estrada esquecida.",
      veioRelation: "Presença espiritual antiga, anterior aos Veios — não é corrompido, é assombração natural.",
      corruptionVisual: null,
      implemented: true,
    },
    {
      id: "espantalho_possuido",
      name: "Espantalho Possuído",
      category: "hostile",
      habitat: "Plantações abandonadas, Sítio (raro)",
      schedule: "night",
      behavior: "Finge estar inerte até o jogador se aproximar; então ataca de surpresa.",
      aggressiveness: 3,
      attacks: ["Emboscada", "Golpe de Palha Afiada"],
      weaknesses: ["Fogo"],
      resistances: ["Perfuração"],
      drops: ["Palha Amaldiçoada"],
      lore: "Espantalhos abandonados por tempo demais às vezes atraem algo que não é mais só palha.",
      veioRelation: "Vaso para pequenos espíritos errantes ligados a terras negligenciadas perto de um Veio.",
      corruptionVisual: "Costuras que brilham fracamente em roxo.",
      implemented: false,
    },
    {
      id: "corpo_seco",
      name: "Corpo-Seco",
      category: "hostile",
      habitat: "Mata do Cedro, Brejo das Lanternas",
      schedule: "night",
      behavior: "Errático e imprevisível; alterna entre lento e explosivamente rápido.",
      aggressiveness: 4,
      attacks: ["Investida Errática", "Sufocamento"],
      weaknesses: ["Água benta / itens de Benzedeiro (futuro)"],
      resistances: ["Dano físico leve"],
      drops: ["Vínculo Podre"],
      lore: "Segundo a lenda, é o corpo de quem morreu sem enterro digno e sem parte de sua alma.",
      veioRelation: "Atraído por Veios como forma de tentar se completar novamente.",
      corruptionVisual: "Pele rachada com fumaça escura escapando das fendas.",
      implemented: false,
    },
    {
      id: "assombracao_da_mina",
      name: "Assombração da Mina",
      category: "hostile",
      habitat: "Mina Santa Luzia (galerias profundas)",
      schedule: "any (interior)",
      behavior: "Atravessa paredes curtas distâncias; resistente a dano físico.",
      aggressiveness: 3,
      attacks: ["Toque Gélido", "Grito Sussurrado"],
      weaknesses: ["Dano espiritual/mágico"],
      resistances: ["Dano físico (alto)"],
      drops: ["Eco de Memória"],
      lore: "Ecos de mineradores que não voltaram — o mesmo destino que Seu Osvaldo teme para seu irmão.",
      veioRelation: "Presas na fronteira entre os dois mundos, bem no ponto onde o Veio da mina vaza.",
      corruptionVisual: "Contorno translúcido com veios negros pulsando por dentro.",
      implemented: false,
    },
    {
      id: "onca_de_bruma",
      name: "Onça de Bruma",
      category: "hostile",
      habitat: "Serra da Onça (fora do MVP), avistada raramente na Mata do Cedro",
      schedule: "neblina",
      behavior: "Mini-boss. Predador raro que desaparece na neblina e reaparece para um ataque surpresa.",
      aggressiveness: 4,
      attacks: ["Emboscada na Neblina", "Investida Tripla"],
      weaknesses: ["Luz concentrada"],
      resistances: ["Furtividade — ignora detecção comum enquanto na neblina"],
      drops: ["Presa de Bruma", "Pelagem Nebulosa"],
      lore: "Predadora que aprendeu a caçar entre os dois mundos, nunca totalmente em nenhum deles.",
      veioRelation: "Não corrompida — uma entidade nativa do Encantado que caça no lado humano.",
      corruptionVisual: null,
      implemented: false,
    },
    {
      id: "carcara_de_ferro",
      name: "Carcará de Ferro",
      category: "boss",
      habitat: "Câmara Funda, Mina Santa Luzia",
      schedule: "any",
      behavior: "Chefe principal do MVP — ver Seção 28 do GDD (3 fases, arena dedicada). Não implementado nesta etapa do protótipo.",
      aggressiveness: 5,
      attacks: ["Bicada", "Rasante", "Rajada de Penas", "Grito do Carcará", "Queda de Pedra", "Ninho Corrompido"],
      weaknesses: ["Ataques concentrados após telegraphs"],
      resistances: ["Fase 3: reduz janelas de punição"],
      drops: ["Fragmento do Encantado"],
      lore: "Vítima, não vilão — uma ave sobrenatural tomada por raízes negras vindas do fundo da mina.",
      veioRelation: "Guardião original do Veio da Mina Santa Luzia, corrompido em sua fonte.",
      corruptionVisual: "Raízes negras entrelaçadas nas asas e penas misturadas a minério.",
      implemented: true,
    },
    {
      id: "saci",
      name: "Saci",
      category: "neutral",
      habitat: "Redemoinhos na Estrada Velha e no Sítio",
      schedule: "any (raro)",
      behavior: "Nunca ataca. Pode pregar peças (esconder um item, trocar uma ferramenta de lugar) e depois devolver se o jogador reagir com bom humor.",
      aggressiveness: 0,
      attacks: [],
      weaknesses: [],
      resistances: [],
      drops: [],
      lore: "Prefere rir de quem se irrita do que brigar com quem ri junto.",
      veioRelation: "Trafega livremente entre os dois mundos por conta própria — não é afetado pela corrupção.",
      corruptionVisual: null,
      implemented: "interactable",
    },
    {
      id: "curupira",
      name: "Curupira",
      category: "guardian",
      habitat: "Mata do Cedro inteira (território)",
      schedule: "any",
      behavior: "Territorial/guardião: não ataca por padrão. Reage à Perturbação da Mata (ver GDD Seção 34) — acima de um limiar, atrapalha a navegação do jogador como aviso antes de qualquer punição maior.",
      aggressiveness: "condicional",
      attacks: ["Confundir Trilhas (não-letal)"],
      weaknesses: [],
      resistances: ["Praticamente invencível em combate direto — não é pensado como inimigo derrotável"],
      drops: [],
      lore: "Protetor da mata, pés virados para trás para confundir quem a agride demais.",
      veioRelation: "Guardião nativo do Encantado, hostil apenas à destruição excessiva, não ao jogador em si.",
      corruptionVisual: null,
      implemented: false,
    },
    {
      id: "boitata",
      name: "Boitatá",
      category: "guardian",
      habitat: "Brejo das Lanternas",
      schedule: "night",
      behavior: "Entidade de fogo associada à proteção da mata contra quem a destrói. Pode se tornar chefe em conteúdo futuro dependendo das ações do jogador.",
      aggressiveness: "condicional",
      attacks: ["Rastro de Fogo (fase de chefe futura)"],
      weaknesses: [],
      resistances: ["Fogo"],
      drops: [],
      lore: "Serpente de fogo que devora os olhos de quem queima a mata sem necessidade, na lenda original.",
      veioRelation: "Guardiã de um Veio ainda não revelado ao jogador no MVP.",
      corruptionVisual: null,
      implemented: false,
    },
    {
      id: "iara",
      name: "Iara",
      category: "narrative",
      habitat: "Rio das Pedras",
      schedule: "madrugada (00h-02h)",
      behavior: "Gatilho da quest 'Pescaria Noturna' (GDD Seção 30) — combate, conversa, seguir ou oferenda geram resultados diferentes.",
      aggressiveness: "depende da escolha do jogador",
      attacks: ["Canto Hipnótico (se atacada)"],
      weaknesses: [],
      resistances: [],
      drops: [],
      lore: "Entidade das águas — nome reaproveitado deliberadamente do folclore, distinto da NPC humana 'Iara, a pescadora' (GDD Seção 24) por contraste narrativo.",
      veioRelation: "Vive próxima a um pequeno vazamento do Veio no leito do rio.",
      corruptionVisual: null,
      implemented: false,
    },
    {
      id: "boto",
      name: "Boto",
      category: "narrative",
      habitat: "Rio das Pedras, em noites de festa na vila",
      schedule: "night (eventos especiais)",
      behavior: "Aparece em forma humana durante eventos comunitários futuros; quest de identidade/confiança.",
      aggressiveness: 0,
      attacks: [],
      weaknesses: [],
      resistances: [],
      drops: [],
      lore: "Reservado para conteúdo pós-MVP — gancho já documentado para não perder a referência.",
      veioRelation: "A definir.",
      corruptionVisual: null,
      implemented: false,
    },
    {
      id: "sombra_do_cafezal",
      name: "Sombra do Cafezal",
      category: "hostile",
      habitat: "Plantações da vila, noites específicas",
      schedule: "night (raro)",
      behavior: "Furtiva — usa medo em vez de dano direto na maior parte do encontro.",
      aggressiveness: 3,
      attacks: ["Sussurro do Medo", "Golpe nas Sombras"],
      weaknesses: ["Luz"],
      resistances: ["Furtividade"],
      drops: ["Grão Sombrio"],
      lore: "Diz-se que ronda plantações onde uma colheita foi perdida por descaso, não por azar.",
      veioRelation: "Atraída por Perturbação alta em terras cultivadas próximas a um Veio.",
      corruptionVisual: "Silhueta com bordas que 'fumegam' escuridão.",
      implemented: false,
    },
  ];

  function getById(id) {
    for (var i = 0; i < list.length; i++) if (list[i].id === id) return list[i];
    return null;
  }

  return {
    CATEGORY_LABEL: CATEGORY_LABEL,
    list: list,
    getById: getById,
  };
})();
